name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Nexus registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CUSTOM_REGISTRY_URL }}
          username: ${{ secrets.CUSTOM_REGISTRY_USERNAME }}
          password: ${{ secrets.CUSTOM_REGISTRY_PASSWORD }}

      - name: Build and push to Nexus registry
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ vars.CUSTOM_REGISTRY_URL }}/cimg/android:2024.04.1

